version: '3.8'
services:
  postgres:
    image: postgres:15.0
    restart: always
    environment:
      - POSTGRES_USER=recipe
      - POSTGRES_PASSWORD=RecipePassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis
    restart: always
    environment:
        - REDIS_PASSWORD=recipe
        - REDIS_PORT=6379
        - REDIS_DATABASES=16
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  postgres:
    driver: local
  redis:
    driver: local